/***************************************************************
* file: MainMenu.java
* author: Sam Lee, Andrew Nipp, Joshua Ludwig, Steven Mai, Je'Don Carter
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Project v1.1
* date last modified: 1/18/2017
*
* purpose: This file is the main menu where the user can choose to play
* the game, see high scores, or see credits.
*
****************************************************************/ 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245.project;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import static cs245.project.Splash.splashInit;
import java.awt.Event;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Date;
import sun.audio.*;
import java.io.*;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.Action;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;

/**
 *
 * @author amnipp
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    HangMan hangman = new HangMan();
    private static int musicControl = 1;
    AudioStream audio = null;
    
    public MainMenu() {
        initComponents();
        currentTime();
        backgroundMusic();
        addBindings();
    }
    
    //method: addBindings
    //purpose: adds keyBindings to the Clock label
    public void addBindings(){
        Action exit = new AbstractAction(){
            public void actionPerformed(ActionEvent e){
                dispose();
                System.exit(0);
            }
        };
        Action credits = new AbstractAction(){
            public void actionPerformed(ActionEvent e){
                System.out.print("test1\n");
                MainMenu menu = new MainMenu();
                CreditsScreen credits = new CreditsScreen();
                menu.setVisible(false);
                credits.setVisible(true);
                dispose();
            }
        };
        String actName = "exit";
        Clock.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"),
                actName);
        Clock.getActionMap().put(actName, exit);
        actName = "credits";
        Clock.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"),
                actName);
        Clock.getActionMap().put(actName, credits);
    }
    
    //background music
    public void backgroundMusic()
    {
        if(musicControl == 1)
        {
        //Play music
        InputStream inaudio = getClass().getResourceAsStream("/Sounds/SW_music.wav");
        try{
            audio = new AudioStream(inaudio);
            AudioPlayer.player.start(audio);
        }
        catch(Exception e)
        {
            System.out.print("File not found");
        }
        musicControl++;
        }
        else
        AudioPlayer.player.stop(audio);
    }
	// method: currentTime
	// purpose: This method will generate and display the current time
	// on the main menu
    public void currentTime() {
        Thread clock = new Thread()
        {
                public void run()
                {
                    for(;;)
                    {
                        Calendar cal = new GregorianCalendar();
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);
                        Date now = new Date();
                        SimpleDateFormat dateFormatter = new SimpleDateFormat("MMMM d, yyyy");
                        Clock.setText(dateFormatter.format(now) + "    " + hour + ": " + minute + ":  " + second);
                        try{
                            sleep(1000);
                        }
                        catch (Exception e)
                        {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Play = new javax.swing.JButton();
        High_Score = new javax.swing.JButton();
        Credits = new javax.swing.JButton();
        Clock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        dark_trooper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Play.setText("Play");
        Play.setToolTipText("Press to play the game.");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        getContentPane().add(Play);
        Play.setBounds(70, 350, 83, 23);

        High_Score.setText("High Score");
        High_Score.setToolTipText("Press to open high score screen.");
        High_Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                High_ScoreActionPerformed(evt);
            }
        });
        getContentPane().add(High_Score);
        High_Score.setBounds(200, 350, 83, 23);

        Credits.setText("Credits");
        Credits.setToolTipText("Press to open the credits screen.");
        Credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditsActionPerformed(evt);
            }
        });
        getContentPane().add(Credits);
        Credits.setBounds(330, 350, 83, 23);

        Clock.setForeground(new java.awt.Color(153, 0, 0));
        Clock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Clock.setText("TIME");
        getContentPane().add(Clock);
        Clock.setBounds(310, 20, 270, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your escort has DIED, ");
        jLabel2.setAutoscrolls(true);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 130, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("guess the extraction codeword to escape the trooper");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 30, 360, 20);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs245/project/icon.png"))); // NOI18N
        icon.setText("jLabel1");
        getContentPane().add(icon);
        icon.setBounds(130, 90, 220, 220);

        dark_trooper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs245/project/trooper_images/star-wars-backgrounds.png"))); // NOI18N
        getContentPane().add(dark_trooper);
        dark_trooper.setBounds(0, 0, 600, 400);

        setSize(new java.awt.Dimension(616, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        // TODO add your handling code here:
        backgroundMusic();
        AudioStream audio = null;
        //Play music
        InputStream inaudio = getClass().getResourceAsStream("/Sounds/Roger_roger.wav");
        try{
            audio = new AudioStream(inaudio);
            AudioPlayer.player.start(audio);
        }
        catch(Exception e)
        {
            System.out.print("File not found");
        }
        //Select a word
        /*String[] WORD_LIST = {"abstract", "cemetery", "nurse", "pharmacy", "climbing"};
        String selectedWord;
        int randIndex = new Random().nextInt(WORD_LIST.length+1);
        selectedWord = WORD_LIST[randIndex];*/
        HangMan hangman = new HangMan();
        hangman.start();
        PlayScreen play = new PlayScreen(hangman);
        hangman.setPlayScreen(play);
        play.setVisible(true);
        setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_PlayActionPerformed

    private void High_ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_High_ScoreActionPerformed
        // TODO add your handling code here:
        HighScoreScreen highScore = new HighScoreScreen();
        MainMenu menu = new MainMenu();
        menu.setVisible(false);
        highScore.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_High_ScoreActionPerformed

    private void CreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditsActionPerformed
        // TODO add your handling code here:
        MainMenu menu = new MainMenu();
        CreditsScreen credits = new CreditsScreen();
        menu.setVisible(false);
        credits.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CreditsActionPerformed

	// method: Main
	// purpose: initialized teh splashscreen then creates the main menu screen
    public static void main(String args[]) {
        splashInit();

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    Thread.sleep(3000);
                }
                catch(Exception e) {
                    
                }
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clock;
    private javax.swing.JButton Credits;
    private javax.swing.JButton High_Score;
    private javax.swing.JButton Play;
    private javax.swing.JLabel dark_trooper;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
