/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245.project;

/**
 *
 * @author Stebo
 */
public class SudokuGUI extends javax.swing.JFrame {

   Sudoku sg;
    public SudokuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        r9_1 = new javax.swing.JTextField();
        r7_1 = new javax.swing.JTextField();
        r8_2 = new javax.swing.JTextField();
        r7_3 = new javax.swing.JTextField();
        r9_3 = new javax.swing.JTextField();
        r7_2 = new javax.swing.JTextField();
        r8_3 = new javax.swing.JTextField();
        r8_1 = new javax.swing.JTextField();
        r9_2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        r5_8 = new javax.swing.JTextField();
        r6_8 = new javax.swing.JTextField();
        r4_8 = new javax.swing.JTextField();
        r5_9 = new javax.swing.JTextField();
        r5_7 = new javax.swing.JTextField();
        r6_9 = new javax.swing.JTextField();
        r4_7 = new javax.swing.JTextField();
        r6_7 = new javax.swing.JTextField();
        r4_9 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        r7_9 = new javax.swing.JTextField();
        r7_8 = new javax.swing.JTextField();
        r9_9 = new javax.swing.JTextField();
        r9_8 = new javax.swing.JTextField();
        r8_7 = new javax.swing.JTextField();
        r8_9 = new javax.swing.JTextField();
        r9_7 = new javax.swing.JTextField();
        r7_7 = new javax.swing.JTextField();
        r8_8 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        r6_3 = new javax.swing.JTextField();
        r4_1 = new javax.swing.JTextField();
        r4_2 = new javax.swing.JTextField();
        r4_3 = new javax.swing.JTextField();
        r5_1 = new javax.swing.JTextField();
        r5_2 = new javax.swing.JTextField();
        r5_3 = new javax.swing.JTextField();
        r6_1 = new javax.swing.JTextField();
        r6_2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        r3_6 = new javax.swing.JTextField();
        r2_4 = new javax.swing.JTextField();
        r1_5 = new javax.swing.JTextField();
        r3_4 = new javax.swing.JTextField();
        r2_6 = new javax.swing.JTextField();
        r2_5 = new javax.swing.JTextField();
        r1_4 = new javax.swing.JTextField();
        r3_5 = new javax.swing.JTextField();
        r1_6 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        r7_5 = new javax.swing.JTextField();
        r8_5 = new javax.swing.JTextField();
        r8_4 = new javax.swing.JTextField();
        r7_4 = new javax.swing.JTextField();
        r7_6 = new javax.swing.JTextField();
        r9_4 = new javax.swing.JTextField();
        r9_5 = new javax.swing.JTextField();
        r9_6 = new javax.swing.JTextField();
        r8_6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        r3_1 = new javax.swing.JTextField();
        r1_2 = new javax.swing.JTextField();
        r2_1 = new javax.swing.JTextField();
        r1_1 = new javax.swing.JTextField();
        r2_2 = new javax.swing.JTextField();
        r3_2 = new javax.swing.JTextField();
        r3_3 = new javax.swing.JTextField();
        r2_3 = new javax.swing.JTextField();
        r1_3 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        r4_5 = new javax.swing.JTextField();
        r5_5 = new javax.swing.JTextField();
        r5_4 = new javax.swing.JTextField();
        r4_6 = new javax.swing.JTextField();
        r5_6 = new javax.swing.JTextField();
        r6_4 = new javax.swing.JTextField();
        r6_6 = new javax.swing.JTextField();
        r4_4 = new javax.swing.JTextField();
        r6_5 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        r2_8 = new javax.swing.JTextField();
        r1_8 = new javax.swing.JTextField();
        r1_9 = new javax.swing.JTextField();
        r3_8 = new javax.swing.JTextField();
        r2_9 = new javax.swing.JTextField();
        r1_7 = new javax.swing.JTextField();
        r3_7 = new javax.swing.JTextField();
        r3_9 = new javax.swing.JTextField();
        r2_7 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 120));

        r9_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_1ActionPerformed(evt);
            }
        });

        r7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_1ActionPerformed(evt);
            }
        });

        r8_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_2ActionPerformed(evt);
            }
        });

        r7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_3ActionPerformed(evt);
            }
        });

        r9_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_3ActionPerformed(evt);
            }
        });

        r7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_2ActionPerformed(evt);
            }
        });

        r8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_3ActionPerformed(evt);
            }
        });

        r8_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_1ActionPerformed(evt);
            }
        });

        r9_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(r7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(r8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r8_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(r9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r9_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 120));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 120));

        r5_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_8ActionPerformed(evt);
            }
        });

        r6_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_8ActionPerformed(evt);
            }
        });

        r4_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_8ActionPerformed(evt);
            }
        });

        r5_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_9ActionPerformed(evt);
            }
        });

        r5_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_7ActionPerformed(evt);
            }
        });

        r6_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_9ActionPerformed(evt);
            }
        });

        r4_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_7ActionPerformed(evt);
            }
        });

        r6_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_7ActionPerformed(evt);
            }
        });

        r4_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r4_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r6_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 120));

        r7_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_9ActionPerformed(evt);
            }
        });

        r7_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_8ActionPerformed(evt);
            }
        });

        r9_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_9ActionPerformed(evt);
            }
        });

        r9_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_8ActionPerformed(evt);
            }
        });

        r8_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_7ActionPerformed(evt);
            }
        });

        r8_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_9ActionPerformed(evt);
            }
        });

        r9_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_7ActionPerformed(evt);
            }
        });

        r7_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_7ActionPerformed(evt);
            }
        });

        r8_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r7_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r8_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r8_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r8_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(r9_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r9_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r9_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r8_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r9_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 120));

        r6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_3ActionPerformed(evt);
            }
        });

        r4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_1ActionPerformed(evt);
            }
        });

        r4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_2ActionPerformed(evt);
            }
        });

        r4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_3ActionPerformed(evt);
            }
        });

        r5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_1ActionPerformed(evt);
            }
        });

        r5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_2ActionPerformed(evt);
            }
        });

        r5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_3ActionPerformed(evt);
            }
        });

        r6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_1ActionPerformed(evt);
            }
        });

        r6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(r4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(r5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(r6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 120));

        r3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_6ActionPerformed(evt);
            }
        });

        r2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_4ActionPerformed(evt);
            }
        });

        r3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_4ActionPerformed(evt);
            }
        });

        r2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_6ActionPerformed(evt);
            }
        });

        r1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_4ActionPerformed(evt);
            }
        });

        r3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(r1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(r2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(r3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(120, 120));

        r7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_5ActionPerformed(evt);
            }
        });

        r8_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_5ActionPerformed(evt);
            }
        });

        r8_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_4ActionPerformed(evt);
            }
        });

        r7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_4ActionPerformed(evt);
            }
        });

        r7_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7_6ActionPerformed(evt);
            }
        });

        r9_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_4ActionPerformed(evt);
            }
        });

        r9_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_5ActionPerformed(evt);
            }
        });

        r9_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9_6ActionPerformed(evt);
            }
        });

        r8_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(r7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(r8_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r8_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(r9_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r9_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r9_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r8_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r9_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(120, 120));

        r3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_1ActionPerformed(evt);
            }
        });

        r1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_2ActionPerformed(evt);
            }
        });

        r2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_1ActionPerformed(evt);
            }
        });

        r1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_1ActionPerformed(evt);
            }
        });

        r3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_2ActionPerformed(evt);
            }
        });

        r3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_3ActionPerformed(evt);
            }
        });

        r2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(r1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(r2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(r3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setPreferredSize(new java.awt.Dimension(120, 120));

        r4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_5ActionPerformed(evt);
            }
        });

        r5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_5ActionPerformed(evt);
            }
        });

        r5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_4ActionPerformed(evt);
            }
        });

        r4_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_6ActionPerformed(evt);
            }
        });

        r5_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5_6ActionPerformed(evt);
            }
        });

        r6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_4ActionPerformed(evt);
            }
        });

        r6_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_6ActionPerformed(evt);
            }
        });

        r4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4_4ActionPerformed(evt);
            }
        });

        r6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(r4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(r5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(r6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setPreferredSize(new java.awt.Dimension(120, 120));

        r3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_8ActionPerformed(evt);
            }
        });

        r2_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_9ActionPerformed(evt);
            }
        });

        r1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_7ActionPerformed(evt);
            }
        });

        r3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_7ActionPerformed(evt);
            }
        });

        r3_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_9ActionPerformed(evt);
            }
        });

        r2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(r1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(r2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(r3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(r3_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jToggleButton1.setText("Quit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jToggleButton2.setText("Submit");
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 16)); // NOI18N
        jLabel1.setText("Sudoku");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void r6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_3ActionPerformed

    private void r4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_1ActionPerformed

    private void r4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_2ActionPerformed

    private void r4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_3ActionPerformed

    private void r5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_1ActionPerformed

    private void r5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_2ActionPerformed

    private void r5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_3ActionPerformed

    private void r6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_1ActionPerformed

    private void r2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2_3ActionPerformed

    private void r3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_1ActionPerformed

    private void r2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2_1ActionPerformed

    private void r3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_2ActionPerformed

    private void r3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_3ActionPerformed

    private void r3_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_9ActionPerformed

    private void r3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_8ActionPerformed

    private void r3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_7ActionPerformed

    private void r3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_4ActionPerformed

    private void r3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_5ActionPerformed

    private void r3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3_6ActionPerformed

    private void r2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2_6ActionPerformed

    private void r2_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2_9ActionPerformed

    private void r2_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2_7ActionPerformed

    private void r2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2_4ActionPerformed

    private void r1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1_4ActionPerformed

    private void r1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1_7ActionPerformed

    private void r1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1_1ActionPerformed

    private void r6_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_6ActionPerformed

    private void r4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_4ActionPerformed

    private void r4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_5ActionPerformed

    private void r4_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_6ActionPerformed

    private void r5_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_6ActionPerformed

    private void r5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_5ActionPerformed

    private void r5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_4ActionPerformed

    private void r6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_4ActionPerformed

    private void r6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_5ActionPerformed

    private void r6_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_9ActionPerformed

    private void r4_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_7ActionPerformed

    private void r4_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_8ActionPerformed

    private void r4_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4_9ActionPerformed

    private void r5_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_9ActionPerformed

    private void r5_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_8ActionPerformed

    private void r5_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5_7ActionPerformed

    private void r6_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_7ActionPerformed

    private void r6_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_8ActionPerformed

    private void r9_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_3ActionPerformed

    private void r9_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_2ActionPerformed

    private void r9_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_1ActionPerformed

    private void r8_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_1ActionPerformed

    private void r7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_1ActionPerformed

    private void r7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_2ActionPerformed

    private void r8_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_2ActionPerformed

    private void r8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_3ActionPerformed

    private void r7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_3ActionPerformed

    private void r9_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_6ActionPerformed

    private void r7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_4ActionPerformed

    private void r7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_5ActionPerformed

    private void r7_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_6ActionPerformed

    private void r8_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_6ActionPerformed

    private void r8_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_5ActionPerformed

    private void r8_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_4ActionPerformed

    private void r9_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_4ActionPerformed

    private void r9_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_5ActionPerformed

    private void r9_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_9ActionPerformed

    private void r7_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_7ActionPerformed

    private void r7_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_8ActionPerformed

    private void r7_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7_9ActionPerformed

    private void r8_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_9ActionPerformed

    private void r8_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_8ActionPerformed

    private void r8_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8_7ActionPerformed

    private void r9_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_7ActionPerformed

    private void r9_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9_8ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void r1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1_2ActionPerformed

    private void r6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField r1_1;
    private javax.swing.JTextField r1_2;
    private javax.swing.JTextField r1_3;
    private javax.swing.JTextField r1_4;
    private javax.swing.JTextField r1_5;
    private javax.swing.JTextField r1_6;
    private javax.swing.JTextField r1_7;
    private javax.swing.JTextField r1_8;
    private javax.swing.JTextField r1_9;
    private javax.swing.JTextField r2_1;
    private javax.swing.JTextField r2_2;
    private javax.swing.JTextField r2_3;
    private javax.swing.JTextField r2_4;
    private javax.swing.JTextField r2_5;
    private javax.swing.JTextField r2_6;
    private javax.swing.JTextField r2_7;
    private javax.swing.JTextField r2_8;
    private javax.swing.JTextField r2_9;
    private javax.swing.JTextField r3_1;
    private javax.swing.JTextField r3_2;
    private javax.swing.JTextField r3_3;
    private javax.swing.JTextField r3_4;
    private javax.swing.JTextField r3_5;
    private javax.swing.JTextField r3_6;
    private javax.swing.JTextField r3_7;
    private javax.swing.JTextField r3_8;
    private javax.swing.JTextField r3_9;
    private javax.swing.JTextField r4_1;
    private javax.swing.JTextField r4_2;
    private javax.swing.JTextField r4_3;
    private javax.swing.JTextField r4_4;
    private javax.swing.JTextField r4_5;
    private javax.swing.JTextField r4_6;
    private javax.swing.JTextField r4_7;
    private javax.swing.JTextField r4_8;
    private javax.swing.JTextField r4_9;
    private javax.swing.JTextField r5_1;
    private javax.swing.JTextField r5_2;
    private javax.swing.JTextField r5_3;
    private javax.swing.JTextField r5_4;
    private javax.swing.JTextField r5_5;
    private javax.swing.JTextField r5_6;
    private javax.swing.JTextField r5_7;
    private javax.swing.JTextField r5_8;
    private javax.swing.JTextField r5_9;
    private javax.swing.JTextField r6_1;
    private javax.swing.JTextField r6_2;
    private javax.swing.JTextField r6_3;
    private javax.swing.JTextField r6_4;
    private javax.swing.JTextField r6_5;
    private javax.swing.JTextField r6_6;
    private javax.swing.JTextField r6_7;
    private javax.swing.JTextField r6_8;
    private javax.swing.JTextField r6_9;
    private javax.swing.JTextField r7_1;
    private javax.swing.JTextField r7_2;
    private javax.swing.JTextField r7_3;
    private javax.swing.JTextField r7_4;
    private javax.swing.JTextField r7_5;
    private javax.swing.JTextField r7_6;
    private javax.swing.JTextField r7_7;
    private javax.swing.JTextField r7_8;
    private javax.swing.JTextField r7_9;
    private javax.swing.JTextField r8_1;
    private javax.swing.JTextField r8_2;
    private javax.swing.JTextField r8_3;
    private javax.swing.JTextField r8_4;
    private javax.swing.JTextField r8_5;
    private javax.swing.JTextField r8_6;
    private javax.swing.JTextField r8_7;
    private javax.swing.JTextField r8_8;
    private javax.swing.JTextField r8_9;
    private javax.swing.JTextField r9_1;
    private javax.swing.JTextField r9_2;
    private javax.swing.JTextField r9_3;
    private javax.swing.JTextField r9_4;
    private javax.swing.JTextField r9_5;
    private javax.swing.JTextField r9_6;
    private javax.swing.JTextField r9_7;
    private javax.swing.JTextField r9_8;
    private javax.swing.JTextField r9_9;
    // End of variables declaration//GEN-END:variables
}
